const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/auth');
const Summary = require('../models/Summary');

// Save new summary (protected)
router.post('/', authMiddleware, async (req, res) => {
    try {
        const { fileName, fileType, summary, keyPoints, fullText } = req.body;

        const newSummary = new Summary({
            userId: req.userId,
            fileName,
            fileType,
            summary,
            keyPoints: keyPoints || [],
            fullText: fullText || ''
        });

        await newSummary.save();

        res.status(201).json({
            message: 'Summary saved successfully',
            summary: newSummary
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Get user's summary history (protected)
router.get('/', authMiddleware, async (req, res) => {
    try {
        const summaries = await Summary.find({ userId: req.userId })
            .sort({ createdAt: -1 })
            .limit(50);

        res.json({
            count: summaries.length,
            summaries
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

const PDFDocument = require('pdfkit');

// ... (existing code)

// Download summary as PDF (protected)
router.get('/:id/download', authMiddleware, async (req, res) => {
    try {
        const summary = await Summary.findOne({
            _id: req.params.id,
            userId: req.userId
        });

        if (!summary) {
            return res.status(404).json({ error: 'Summary not found' });
        }

        const doc = new PDFDocument();

        // Set filename
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=summary-${summary.fileName}.pdf`);

        doc.pipe(res);

        // Styling the PDF
        doc.fontSize(24).font('Helvetica-Bold').text('Document Intelligence Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(14).font('Helvetica').text(`File: ${summary.fileName}`, { color: 'grey' });
        doc.text(`Date: ${new Date(summary.createdAt).toLocaleDateString()}`);
        doc.moveDown();

        doc.fontSize(18).font('Helvetica-Bold').text('Executive Summary');
        doc.moveDown(0.5);
        doc.fontSize(12).font('Helvetica').text(summary.summary, { align: 'justify', lineGap: 5 });
        doc.moveDown();

        if (summary.keyPoints && summary.keyPoints.length > 0) {
            doc.fontSize(18).font('Helvetica-Bold').text('Key Highlights');
            doc.moveDown(0.5);
            summary.keyPoints.forEach(point => {
                doc.fontSize(12).font('Helvetica').text(`• ${point}`, { indent: 20 });
            });
        }

        doc.moveDown(2);
        doc.fontSize(10).font('Helvetica-Oblique').text('Generated by Axon Intelligence Engine', { align: 'center', color: 'grey' });

        doc.end();

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

const { GoogleGenerativeAI } = require("@google/generative-ai");

// ... (existing code)

// Chat with Document (RAG) (protected)
router.post('/:id/chat', authMiddleware, async (req, res) => {
    try {
        const { message } = req.body;

        // Check for API key
        if (!process.env.GEMINI_API_KEY) {
            console.error('Missing GEMINI_API_KEY in environment variables');
            return res.status(500).json({
                error: 'Gemini API key is not configured on the server. Please check environment variables on your hosting provider (e.g., Render).'
            });
        }

        const summary = await Summary.findOne({
            _id: req.params.id,
            userId: req.userId
        });

        if (!summary) return res.status(404).json({ error: 'Summary not found' });

        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
        const context = summary.fullText || summary.summary;

        // Comprehensive list of models to try for free/standard tiers
        const modelsToTry = [
            "gemini-1.5-flash-latest",
            "gemini-1.5-flash",
            "gemini-pro",
            "gemini-1.5-pro",
            "gemini-1.5-flash-8b",
            "gemini-1.0-pro"
        ];

        let responseText = null;
        let lastError = null;
        let attemptedModels = [];

        for (const modelName of modelsToTry) {
            attemptedModels.push(modelName);
            try {
                console.log(`📡 [V3] Attempting Gemini model: ${modelName}...`);
                const model = genAI.getGenerativeModel({ model: modelName });

                const prompt = `
                    You are an AI assistant analyzing a document. 
                    Document Context: ${context}
                    
                    User Question: ${message}
                    
                    Answer the question based ONLY on the document context provided. If the answer is not in the context, say you don't know. 
                    Keep it professional and concise.
                `;

                const result = await model.generateContent(prompt);

                if (result && result.response) {
                    responseText = result.response.text();
                    if (responseText) {
                        console.log(`✅ [V3] Success with model: ${modelName}`);
                        break;
                    }
                }
            } catch (err) {
                const errStr = String(err).toLowerCase();
                console.warn(`⚠️ [V3] Model ${modelName} failed:`, err.message);

                lastError = err;

                // Continue to next model if it's a model-not-found, version issue, or unsupported error
                const isNotFoundError = errStr.includes('not found') || errStr.includes('404');
                const isUnsupportedError = errStr.includes('not supported') || errStr.includes('unsupported') || errStr.includes('not available');

                if (isNotFoundError || isUnsupportedError) {
                    continue;
                } else {
                    // Stop if it's a critical error like 401 (Invalid Key) or 429 (Quota)
                    break;
                }
            }
        }

        if (!responseText) {
            const finalError = lastError ? lastError.message : 'All models failed';
            console.error('Final Chat Error After Multiple Attempts:', finalError);
            return res.status(500).json({
                error: `[V3_MODEL_ERROR] Gemini Error: ${finalError}. (Models tried: ${attemptedModels.join(', ')}). Please verify your API key in Google AI Studio.`
            });
        }

        res.json({ reply: responseText });

    } catch (error) {
        console.error('Chat Error Details:', error);

        // Handle specific Gemini errors if possible
        let errorMessage = error.message;
        if (error.message.includes('API_KEY_INVALID')) {
            errorMessage = 'Invalid Gemini API key. Please check your configuration.';
        } else if (error.message.includes('SAFETY')) {
            errorMessage = 'The response was blocked due to safety filters.';
        }

        res.status(500).json({ error: errorMessage });
    }
});

// Delete summary (protected)
router.delete('/:id', authMiddleware, async (req, res) => {
    try {
        const summary = await Summary.findOne({
            _id: req.params.id,
            userId: req.userId
        });

        if (!summary) {
            return res.status(404).json({ error: 'Summary not found' });
        }

        await summary.deleteOne();

        res.json({ message: 'Summary deleted successfully' });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

module.exports = router;
